PRN221_Project/Pages/Classes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;

namespace PRN221_Project.Pages.Classes
{
    public class EditModel : PageModel
    {
        private readonly PRN221_ProjectContext context;

        public EditModel(PRN221_ProjectContext _context)
        {
            this.context = _context;
        }

        public Calender2 Calendar { get; private set; }
        public string ErrorMessage { get; set; }


        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Calendar = context.Calender2s.FirstOrDefault(x => x.Id == id); 

            if (Calendar == null)
            {
                return NotFound();
            }

            return Page();
        }

        public IActionResult OnPost(int id, string txtClass, string txtSubject, string txtTeacher, string txtRoom, string txtTime)
        {
            var calendarToUpdate = context.Calender2s.Find(id);

            if (calendarToUpdate == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (!IsValidTimeSlot(txtTime))
            {
                ErrorMessage =  "Invalid time slot.";
                Calendar = context.Calender2s.Find(id);

                return Page();
            }

            if (IsDuplicateEntry(txtClass, txtSubject, txtTeacher, txtRoom, txtTime))
            {
                ErrorMessage = "Duplicate entry.";
                Calendar = context.Calender2s.Find(id);
                return Page();
            }

            if (!CheckConflict(txtClass, txtSubject, txtTeacher, txtRoom, txtTime))
            {
               ErrorMessage = "Conflict detected.";
                Calendar = context.Calender2s.Find(id);
               return Page();
            }

            calendarToUpdate.Class = txtClass;
            calendarToUpdate.Subject = txtSubject;
            calendarToUpdate.Teacher = txtTeacher;
            calendarToUpdate.Room = txtRoom;
            calendarToUpdate.Session = txtTime.Substring(0, 1);
            calendarToUpdate.Slot1 = int.Parse(txtTime.Substring(1, 1));
            calendarToUpdate.Slot2 = int.Parse(txtTime.Substring(2, 1));

            try
            {
                context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CalendarExists(calendarToUpdate.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Redirect("/Home");
        }


        private bool CalendarExists(int id)
        {
            return context.Calender2s.Any(e => e.Id == id);
        }

        private bool IsValidTimeSlot(string timeSlot)
        {
            const string ValidTimeSlots = "A24,A35,A46,A52,A63,A42,A53,A64,A25,A36,P24,P35,P46,P52,P63,P42,P53,P64,P25,P36";
            return ValidTimeSlots.Split(',').Contains(timeSlot);
        }

        private bool IsDuplicateEntry(string clast, string subject, string teacher, string room, string timeSlot)
        {
            return context.Calender2s.Any(item =>
                item.Class == clast &&
                item.Subject == subject &&
                item.Teacher == teacher &&
                item.Room == room &&
                item.Session == timeSlot.Substring(0, 1) &&
                item.Slot1 == int.Parse(timeSlot.Substring(1, 1)) &&
                item.Slot2 == int.Parse(timeSlot.Substring(2, 1))
            );
        }

        private bool CheckConflict(string clast, string subject, string teacher, string room, string time)
        {
            return !context.Calender2s.Any(item =>
                (item.Room == room && (item.Session + item.Slot1 + item.Slot2) == time && (item.Class != clast || item.Teacher != teacher || item.Subject != subject)) ||
                (item.Class == clast && item.Session == time.Substring(0, 1) && item.Slot1 == int.Parse(time.Substring(1, 1)) && item.Slot2 == int.Parse(time.Substring(2, 1)) && (item.Room != room || item.Teacher != teacher || item.Subject != subject)) ||
                ((item.Session + item.Slot1 + item.Slot2) == time && item.Teacher == teacher && (item.Room != room || item.Class != clast || item.Subject != subject)));
        }
    }
}

PRN221_Project/Pages/Classes/Management.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PRN221_Project.Models;
using System.Diagnostics;

namespace PRN221_Project.Pages.Classes
{
    public class ManagementModel : PageModel
    {
        private readonly PRN221_ProjectContext context;

        public ManagementModel(PRN221_ProjectContext context)
        {
            this.context = context;
        }

        public List<Calender2> Calendars { get; set; }

        public string ErrorMessage { get; set; }



        public IActionResult OnPost(IFormFile file)
        {
            if (file == null || file.Length <= 0)
            {
                ModelState.AddModelError(string.Empty, "Please select a file.");
                return Page();
            }

            if (!file.FileName.EndsWith(".csv", StringComparison.OrdinalIgnoreCase))
            {
                ModelState.AddModelError(string.Empty, "Please select a CSV file.");
                return Page();
            }

            try
            {
                using (var reader = new StreamReader(file.OpenReadStream()))
                {
                    string line;
                    while ((line = reader.ReadLine()) != null)
                    {
                        var values = line.Split(',');
                        if (values.Length != 5)
                        {
                            continue;
                        }

                        string clast = values[0];
                        string subject = values[1];
                        string teacher = values[2];
                        string room = values[3];
                        string timeSlot = values[4].Trim().ToUpper();

                        if (!IsValidTimeSlot(timeSlot) || IsDuplicateEntry(clast, subject, teacher, room, timeSlot) || !CheckConflict(clast, subject, teacher, room, timeSlot))
                        {
                            continue;
                        }

                        context.Calender2s.Add(new Calender2
                        {
                            Class = clast,
                            Subject = subject,
                            Teacher = teacher,
                            Room = room,
                            Session = timeSlot.Substring(0, 1),
                            Slot1 = int.Parse(timeSlot.Substring(1, 1)),
                            Slot2 = int.Parse(timeSlot.Substring(2, 1))
                        });
                    }

                    context.SaveChanges();
                }

                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error importing CSV file: {ex.Message}");
                return Page();
            }
        }


        private bool IsValidTimeSlot(string timeSlot)
        {
            const string ValidTimeSlots = "A24,A35,A46,A52,A63,A42,A53,A64,A25,A36,P24,P35,P46,P52,P63,P42,P53,P64,P25,P36";
            return ValidTimeSlots.Split(',').Contains(timeSlot);
        }

        private bool IsDuplicateEntry(string clast, string subject, string teacher, string room, string timeSlot)
        {
            return context.Calender2s.Any(item =>
                item.Class == clast &&
                item.Subject == subject &&
                item.Teacher == teacher &&
                item.Room == room &&
                item.Session == timeSlot.Substring(0,1) &&
                item.Slot1 == int.Parse(timeSlot.Substring(1, 1)) &&
                item.Slot2 == int.Parse(timeSlot.Substring(2, 1))
            );
        }

        private bool CheckConflict(string clast, string subject, string teacher, string room, string time)
        {
            return !context.Calender2s.Any(item =>
                (item.Room == room && (item.Session + item.Slot1 + item.Slot2) == time && (item.Class != clast || item.Teacher != teacher || item.Subject != subject)) ||
                (item.Class == clast && item.Session == time.Substring(0,1) && item.Slot1 == int.Parse(time.Substring(1, 1)) && item.Slot2 == int.Parse(time.Substring(2, 1)) && (item.Room != room || item.Teacher != teacher || item.Subject != subject)) ||
                ((item.Session + item.Slot1 + item.Slot2) == time && item.Teacher == teacher && (item.Room != room || item.Class != clast || item.Subject != subject)));
        }

        public IActionResult OnGet()
        {
            Calendars = context.Calender2s.ToList();
            return Page();
        }

        public IActionResult OnPostAdd(string txtClass, string txtSubject, string txtTeacher, string txtRoom, string txtTime)
        {
            if (!IsValidTimeSlot(txtTime))
            {
                ModelState.AddModelError(string.Empty, "Invalid time slot.");
                ErrorMessage = "Invalid time slot.";

                Calendars = context.Calender2s.ToList();
                return Page();
            }

            if (IsDuplicateEntry(txtClass, txtSubject, txtTeacher, txtRoom, txtTime))
            {
                ModelState.AddModelError(string.Empty, "Duplicate entry.");
                ErrorMessage = "Duplicate entry.";

                Calendars = context.Calender2s.ToList();
                return Page();
            }

            if (!CheckConflict(txtClass, txtSubject, txtTeacher, txtRoom, txtTime))
            {
                ModelState.AddModelError(string.Empty, "Conflict detected.");
                ErrorMessage = "Conflict detected.";

                Calendars = context.Calender2s.ToList();

                return Page();
            }

            var newCalendar = new Calender2
            {
                Class = txtClass,
                Subject = txtSubject,
                Teacher = txtTeacher,
                Room = txtRoom,
                Session = txtTime.Substring(0,1),
                Slot1 = int.Parse(txtTime.Substring(1,1)),
                Slot2 = int.Parse(txtTime.Substring(2, 1))
            };

            context.Calender2s.Add(newCalendar);
            context.SaveChanges();

            return RedirectToPage();
        }

        public IActionResult OnPostDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var calendar = context.Calender2s.Find(id);

            if (calendar == null)
            {
                return NotFound();
            }

            context.Calender2s.Remove(calendar);
            context.SaveChanges();

            return RedirectToPage();
        }

    }
}

PRN221_Project/Pages/Classes/TimeTable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Project.Models;


namespace PRN221_Project.Pages.Classes
{
    public class TimeTableModel : PageModel
    {
        private readonly PRN221_ProjectContext _context;

        public TimeTableModel(PRN221_ProjectContext context)
        {
            _context = context;
            TimeSlot = new Dictionary<Tuple<int, int>, Calender2>();
        }

        public Dictionary<Tuple<int, int>, Calender2> TimeSlot;

        public List<Calender2> Calendars { get; set; }

        public List<Calender2> list { get; set; }

        public void OnGet(String? teacher)
        {
            
            Calendars = _context.Calender2s.Where(x => x.Teacher.Equals(teacher)).ToList();
            list = _context.Calender2s.ToList();
            foreach (var c in Calendars)
            {
                int session = getSession(c.Session);
                Tuple<int, int> tuple = Tuple.Create(1 + session, c.Slot1);
                Tuple<int, int> tuple2 = Tuple.Create(2 + session, c.Slot2);

                
                TimeSlot.Add(tuple, c);
                TimeSlot.Add(tuple2, c);

            }
        }

        public int getSession(string session)
        {
            if (session.Equals("A"))
            {
                return 0;
            }
            if (session.Equals("P"))
            {
                return 2;
            }
            return 0;
        }
    }
}

PRN221_Project/Pages/Classes/Edit.cshtml
@page "/Edit"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PRN221_Project.Pages.Classes.EditModel
@{
    var calendar = Model.Calendar;
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>Edit</h1>
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }
        <form method="post">
            <input type="hidden" />
            <div class="form-group">
                <label for="txtClass">Class:</label>
                <input type="text" class="form-control" id="txtClass" name="txtClass" value="@calendar.Class" />
            </div>
            <div class="form-group">
                <label for="txtSubject">Subject:</label>
                <input type="text" class="form-control" id="txtSubject" name="txtSubject" value="@calendar.Subject" />
            </div>
            <div class="form-group">
                <label for="txtTeacher">Teacher:</label>
                <input type="text" class="form-control" id="txtTeacher" name="txtTeacher" value="@calendar.Teacher" />
            </div>
            <div class="form-group">
                <label for="txtRoom">Room:</label>
                <input type="text" class="form-control" id="txtRoom" name="txtRoom" value="@calendar.Room" />
            </div>
            <div class="form-group">
                <label for="txtTime">Time Slot:</label>
                <input type="text" class="form-control" id="txtTime" name="txtTime" value="@calendar.Session@calendar.Slot1@calendar.Slot2" />
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</body>

PRN221_Project/Pages/Classes/Management.cshtml
@page "/Home"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PRN221_Project.Pages.Classes.ManagementModel
@{
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>List of Class</h1>
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="file">Import CSV file:</label>
                <input type="file" class="form-control-file" id="file" name="file">
            </div>
            <button type="submit" class="btn btn-primary">Import</button>
        </form>

        <a href="/TimeTable">View Schedule</a>

        <form asp-page-handler="Add" method="post">
            <div class="form-group">
                <label for="txtClass">Class:</label>
                <input type="text" id="txtClass" name="txtClass" class="form-control">
            </div>
            <div class="form-group">
                <label for="txtSubject">Subject:</label>
                <input type="text" id="txtSubject" name="txtSubject" class="form-control">
            </div>
            <div class="form-group">
                <label for="txtTeacher">Teacher:</label>
                <input type="text" id="txtTeacher" name="txtTeacher" class="form-control">
            </div>
            <div class="form-group">
                <label for="txtRoom">Room:</label>
                <input type="text" id="txtRoom" name="txtRoom" class="form-control">
            </div>
            <div class="form-group">
                <label for="txtTime">Time:</label>
                <input type="text" id="txtTime" name="txtTime" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Add</button>
        </form>

        <table class="table mt-5">
            <thead>
                <tr>
                    <th>Class</th>
                    <th>Subject</th>
                    <th>Teacher</th>
                    <th>Room</th>
                    <th>TimeSlot</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Calendars)
                {
                    <tr>
                        <td>@item.Class</td>
                        <td>@item.Subject</td>
                        <td>@item.Teacher</td>
                        <td>@item.Room</td>
                        <td>@item.Session@item.Slot1@item.Slot2</td>
                        <td>
                            <form asp-page-handler="Delete" method="post">
                                <input type="hidden" name="id" value="@item.Id">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            <form asp-page="./Edit" method="get">
                                <input type="hidden" name="id" value="@item.Id">
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script>
        document.getElementById("selectTeacher").addEventListener("change", function () {
            var selectedTeacher = this.value; 
            if (selectedTeacher) {
                window.location.href = "/TimeTable?teacher=" + selectedTeacher;
            }
        });
    </script>
</body>

PRN221_Project/Pages/Classes/TimeTable.cshtml
@page "/TimeTable"
@model PRN221_Project.Pages.Classes.TimeTableModel
@using  PRN221_Project.Models
@{
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ClassTimeTable</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: lightgray;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Schedule</h1>
        <div class="mb-3">
            <label for="teacherSelect" class="form-label">Select Class:</label>
            <select class="form-select" id="teacherSelect">
                <option value="">-- Select Teacher --</option>
                @foreach (var teacher in Model.list.Select(c => c.Teacher).Distinct())
                {
                    <option value="@teacher">@teacher</option>
                }
            </select>
        </div>
        <table class="table" id="classTimeTable">
            <thead>
                <tr>
                    <th></th>
                    <th scope="col">Monday</th>
                    <th scope="col">Tuesday</th>
                    <th scope="col">Wednesday</th>
                    <th scope="col">Thursday</th>
                    <th scope="col">Friday</th>
                </tr>
            </thead>
            <tbody>
               
                @for(int i = 1; i <=4;i++){
                    <tr>
                        <td>Slot @i</td>
                    @for(int j = 2; j <= 6; j++)
                    {
                        var key = Tuple.Create(i, j);
                        Calender2 calender2 = new Calender2();
                        if(Model.TimeSlot.TryGetValue(key,out calender2))
                        {
                            <td>@calender2.Teacher <br /> @calender2.Room<br />@calender2.Subject</td>
                        }else{
                            <td></td>
                        }
                    }
                    </tr>

                }
            </tbody>
        </table>
    </div>

    <script>
        document.getElementById("teacherSelect").addEventListener("change", function () {
            var selectedTeacher = this.value;
            window.location.href = "/TimeTable?teacher=" + selectedTeacher;
        });
    </script>
</body>